name: 'Terraform Orchestration Action'
description: 'This action is used to orchestrate Terraform modules. It searches for a Terraform module in the current directory which has been modified and runs Terraform inside the module.'
inputs:
  workingDirectory:
    description: 'Working directory to run Terraform in.'
    required: false
    default: '.'
  baseRef:
    description: 'Git reference to use as the base'
    required: true
  headRef:
    description: 'Git reference to use as the head'
    required: true
  excludeDirectories:
    description: 'List of directories separated by commas to exclude from the search'
    required: false
  workspace:
    description: 'Workspace to use for Terraform'
    required: true
  apply:
    description: 'Boonlean variable to determine if the action should apply the changes'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'gray-dark'
