name: 'Terraform Orchestration Action'
description: 'This action is used to orchestrate Terraform modules which has been changed.'
inputs:
  workingDirectory:
    description: 'Working directory to run Terraform in.'
    required: false
    default: '.'
  baseRef:
    description: 'Git reference to use as the base'
    required: true
  headRef:
    description: 'Git reference to use as the head'
    required: true
  excludeDirectories:
    description: 'List of directories separated by commas to exclude from the search'
    required: false
  commonModules:
    description: 'List of common modules, if you change some common modules, all components will be updated'
    required: false
  workspace:
    description: 'Workspace to use for Terraform'
    required: true
  apply:
    description: 'Boolean variable to determine if the action should apply the changes'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'gray-dark'
