name: Test
on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 0.14.3

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '15.5'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ hashFiles('**/yarn.lock') }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
