name: Test
on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 0.14.3

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ hashFiles('**/yarn.lock') }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build

      - name: action test plan
        uses: ./
        with:
          workingDirectory: __tests__/tf_project/
          excludeDirectories: __tests__/tf_project/010-second
          baseRef: 86e35d7e707289588dcf6f825be3e7c3e854cf58
          headRef: 009ec5a0e9196b668d926916eaeb6f778694074f

      - name: action test apply
        uses: ./
        with:
          workingDirectory: __tests__/tf_project/
          excludeDirectories: __tests__/tf_project/010-second
          baseRef: 86e35d7e707289588dcf6f825be3e7c3e854cf58
          headRef: 009ec5a0e9196b668d926916eaeb6f778694074f
          apply: true

      - name: action test
        uses: ./
        with:
          workingDirectory: __tests__/tf_project/
          baseRef: ${{ github.event.pull_request.base.sha }}
          headRef: ${{ github.event.pull_request.head.sha }}
