name: Test
on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 0.13.5

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '15.5'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ hashFiles('**/yarn.lock') }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: git log
      - run: git diff --name-only 86e35d7e707289588dcf6f825be3e7c3e854cf58..009ec5a0e9196b668d926916eaeb6f778694074f
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
